### ISSUE TITLE
Change Bootstrap to Foundation

### ISSUE THREAD

**Issue by Reltre** [emillipede/street-tree-map#20]
Note: PR #19 is blocking for this task

⚡️ This is a quick update, but going forward, it looks like Foundation may be more flexible than bootstrap. Let's update the current visual framework from bootstrap to foundation.  ⚡️ 

### Resources

https://foundation.zurb.com/
https://react.foundation/
https://www.npmjs.com/package/react-foundation

**Comment by acostajake** [comment]
Bootstrap removed along with unused/needed styled-components. Foundation added as dependency.

**Comment by ian-r-rose** [comment]
Fixed by #23
